### ISSUE TITLE
X overflow on the website

### ISSUE THREAD

**Issue by ghost** [reactxsw/Smilewinbot#26]
# There is X overflow on the website:
![image](https://user-images.githubusercontent.com/84878036/153319101-66581329-fbe7-4ae3-947e-1d528d1b1197.png)

# Fixes
I would recommend refactoring all the HTML/CSS on starting under the Team Members category, I'll list some things you could do:
- Align the `Team Members` text along with the description of that text.
- Hide the X overflow of course; throw this CSS in the body tag: `overflow-x: hidden;`
- Throw the pictures of the team members into a carousel or something, im pretty sure thats where most of the X overflow is coming from.

**Comment by ghost** [comment]
Hope this helps, I might just fix the code myself and make a pull request at some point I don't know.

**Comment by reactxsw** [comment]
I would appreciate it if you could make a pull request. Thank you

**Comment by ghost** [comment]
I'll get to it in a few days or so, is that ok with you?
Oh and also I have confirmed that the X-overflow is coming from the Team Members sections of the page

**Comment by ghost** [comment]
I came up with a simple carousel that uses a x-axis scrollbar
![image](https://user-images.githubusercontent.com/84878036/153488025-4af62603-4697-4f32-8ba6-3a7f88d40468.png)
Dont mind the colors they will be changed to compliment the already existing website.
### code
```css
<style>
  .slides {
    display: flex;
    overflow-x: auto;
    scroll-snap-type: x mandatory;
  }


  .slides > div {
    display: flex;
    flex-shrink: 0;
    width: 100%;
    scroll-snap-align: start;
    scroll-behavior: smooth;
    background: #74ABE2;
    justify-content: center;
    align-items: center;
  }
</style>
<link rel="stylesheet" href="assets/css/main.css">

<div class="slides">
  <div>
    <figure>
        <img class="rounded" src="https://cdn.discordapp.com/avatars/394447088970104833/10499ed48de3c7cf6417afeca6b81596.png?size=1024" width="250" height="250"> 
        <figcaption style="font-family: 'Kanit', sans-serif;">chamu#3306<br>Marketing </figcaption>
    </figure>
  </div>
  <div>
    <figure>
        <img class="rounded" src="https://cdn.discordapp.com/avatars/394447088970104833/10499ed48de3c7cf6417afeca6b81596.png?size=1024" width="250" height="250"> 
        <figcaption style="font-family: 'Kanit', sans-serif;">chamu#3306<br>Marketing </figcaption>
    </figure>
  </div>
</div>
```
